sudo: required

dist: xenial

language: c

compiler:  
    - gcc

before_script:
    - sudo apt-get -qq update && sudo apt-get install -y libgsl-dev
    - mkdir _build
    - cd _build
    - cmake ..

script: make  