sudo: required

dist: jammy

language: c

branches:
  only:
  - master

compiler:
    - gcc

before_script:
    - sudo apt-get -qq update && sudo apt-get install -y libgsl0-dev
    - mkdir _build
    - cd _build
    - cmake ..

script: make  

notifications:
    email: false