sudo: required

dist: trusty

language: c

compiler:
    - gcc

before_script:
    - sudo apt-get -qq update && sudo apt-get install -y libgsl0-dev
    - mkdir _build
    - cd _build
    - cmake ..

script: make  